# Generated by Django 5.0.3 on 2024-05-09 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('spot_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Skatepark', 'Skatepark'), ('Pumptrack', 'Pumptrack'), ('Bowl', 'Bowl')], max_length=20, null=True)),
                ('conditions', models.CharField(blank=True, choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('beginner', models.BooleanField(blank=True, default=False, null=True)),
                ('intermediate', models.BooleanField(blank=True, default=False, null=True)),
                ('pro', models.BooleanField(blank=True, default=False, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
